version: "3.11"

services:

    api:
      build:
        context: .
      env_file:
        - .env
      container_name: api
      expose:
        - 8000
      ports:
        - 8000:8000
      command: [ "/docker/api.sh" ]
      depends_on:
        postgres:
          condition: service_healthy

    postgres:
      image: postgres:15.1-alpine
      container_name: db
      command: -p 5432
      expose:
        - 5432
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=${DB_USER:?err}
        - POSTGRES_PASSWORD=${DB_PASS:?err}
        - POSTGRES_DB=${DB_NAME:?err}
      volumes:
        - postgres_db:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5

    postgres_test:
      image: postgres:15.1-alpine
      container_name: test_db
      command: -p 5555
      expose:
        - 5555
      ports:
        - 5555:5555
      environment:
        - POSTGRES_USER=${DB_USER_TEST:?err}
        - POSTGRES_PASSWORD=${DB_PASS_TEST:?err}
        - POSTGRES_DB=${DB_NAME_TEST:?err}
      volumes:
        - postgres_db_test:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready", "-U", "postgres_test" ]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  postgres_db:
  postgres_db_test: