version: "3.11"

services:

    postgres_test:
      image: postgres:15.1-alpine
      container_name: test_db
      command: -p 5555
      expose:
        - 5555
      ports:
        - 5555:5555
      environment:
        - POSTGRES_USER=${DB_USER_TEST:?err}
        - POSTGRES_PASSWORD=${DB_PASS_TEST:?err}
        - POSTGRES_DB=${DB_NAME_TEST:?err}
