version: "3.11"

services:

    api:
      build:
        context: .
      env_file:
        - .env
      container_name: api
      restart: on-failure
      expose:
        - 8000
      ports:
        - 8000:8000
      command: [ "/docker/api.sh" ]
      # TODO Добавить проверку redis, rabbitmq, Celery и Flower
      depends_on:
        postgres:
          condition: service_healthy

    redis:
      image: redis:7.2
      container_name: redis
      restart: always
      command: --port 6379
      expose:
        - 6379
      ports:
        - 6379:6379

    # TODO Добавить Celery
    # TODO Добавить Flower

    rabbitmq:
      image: rabbitmq:3.10.7-management
      container_name: rabbitmq
      hostname: rabbitmq
      restart: always
      expose:
        - 15672
        - 5672
      ports:
        - 15672:15672
        - 5672:5672
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:?err}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:?err}
        # Увеличиваем свободное место для записи до 2 ГБ
        # Устанавливаем уровень логирования - error
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
      volumes:
        - rabbitmq:/var/lib/rabbitmq

    postgres:
      image: postgres:15.1-alpine
      container_name: db
      restart: always
      command: -p 5432
      expose:
        - 5432
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=${DB_USER:?err}
        - POSTGRES_PASSWORD=${DB_PASS:?err}
        - POSTGRES_DB=${DB_NAME:?err}
      volumes:
        - postgres_db:/var/lib/postgresql/data
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
  postgres_db:
  rabbitmq:
