version: "3.11"

services:

    test_api:
      build:
        context: .
        dockerfile: Dockerfile-test
      env_file:
        - .env
      container_name: test_api
      expose:
        - 8000
      ports:
        - 8000:8000
      command: [ "/docker/test.sh" ]

    test_postgres:
      image: postgres:15.1-alpine
      container_name: test_db
      restart: always
      command: -p 5433
      expose:
        - 5433
      ports:
        - 5433:5433
      environment:
        - POSTGRES_USER=${DB_USER_TEST:?err}
        - POSTGRES_PASSWORD=${DB_PASS_TEST:?err}
        - POSTGRES_DB=${DB_NAME_TEST:?err}

    test_cache:
      image: redis:7.2
      container_name: test_cache
      restart: always
      command: --port 6379
      expose:
        - 6379
      ports:
        - 6379:6379
