[tool.pytest.ini_options]

# Метоположение тестируемого API для Pytest
pythonpath = [
  ".", "src",
]

# Кастомные маркеры для быстрого запуска тестов нужной категории, н-р: pytest -v -m token
markers = [
    "routes: проверка роутов",
    # TODO Добавить ли тег для integration-тестов или все интеграционные тесты - это роуты?

    "unit: проверка методов в сервисах",
    "fail: проверка при передаче невалидных данных",
#    "user: тесты для проверки вывода данных о пользователе",
#    "tweet: тесты для проверки создания, вывода и удаления твитов",
#    "like: тесты для проверки создания и удаления лайков",
#    "follower: тесты для проверки создания и удаления подписок между пользователями",
#    "image: тесты для проверки загрузки изображений к твитам",
]


# Игнорировать предупреждения DeprecationWarning
#filterwarnings = [
#    "ignore::DeprecationWarning",
#]

# Для нормальной отработки асинхронных функций Pytest
asyncio_mode="auto"