[tool.pytest.ini_options]

# Метоположение тестируемого API для Pytest
pythonpath = [
  ".", "src",
]

# Кастомные маркеры для быстрого запуска тестов нужной категории, н-р: pytest -v -m token
markers = [
    "integration: проверка роутов",
    "unit: проверка методов в сервисах",
    "fail: проверка при передаче невалидных данных",
]


# Игнорировать предупреждения DeprecationWarning
filterwarnings = [
    "ignore::DeprecationWarning",
]

# Для нормальной отработки асинхронных функций Pytest
asyncio_mode="auto"
