"""Add discount colum in dish table

Revision ID: b4340fd0babf
Revises: e0bb34ba6667
Create Date: 2024-02-10 15:08:53.951102

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b4340fd0babf'
down_revision: str | None = 'e0bb34ba6667'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('discount', sa.Integer(), nullable=False))
    op.alter_column('dish', 'price',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=2),
                    existing_nullable=False)
    op.create_unique_constraint(None, 'dish', ['title'])
    op.create_unique_constraint(None, 'menu', ['title'])
    op.create_unique_constraint(None, 'submenu', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submenu', type_='unique')
    op.drop_constraint(None, 'menu', type_='unique')
    op.drop_constraint(None, 'dish', type_='unique')
    op.alter_column('dish', 'price',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=False)
    op.drop_column('dish', 'discount')
    # ### end Alembic commands ###
