"""Delete hash model

Revision ID: e4f1ff7eeae4
Revises: fd4ca9d0e62a
Create Date: 2024-02-12 11:04:27.079993

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4f1ff7eeae4'
down_revision: str | None = 'fd4ca9d0e62a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_hash_hash', table_name='hash')
    op.drop_table('hash')
    op.alter_column('dish', 'price',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=2),
                    existing_nullable=False)
    op.drop_constraint('dish_title_key', 'dish', type_='unique')
    op.drop_constraint('menu_title_key', 'menu', type_='unique')
    op.drop_constraint('submenu_title_key', 'submenu', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('submenu_title_key', 'submenu', ['title'])
    op.create_unique_constraint('menu_title_key', 'menu', ['title'])
    op.create_unique_constraint('dish_title_key', 'dish', ['title'])
    op.alter_column('dish', 'price',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=False)
    op.create_table('hash',
                    sa.Column('hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
                    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('hash', name='hash_pkey')
                    )
    op.create_index('ix_hash_hash', 'hash', ['hash'], unique=False)
    # ### end Alembic commands ###
