"""Add hash model

Revision ID: fd4ca9d0e62a
Revises: b4340fd0babf
Create Date: 2024-02-11 22:26:37.380856

"""
from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fd4ca9d0e62a'
down_revision: str | None = 'b4340fd0babf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hash',
                    sa.Column('hash', sa.String(length=64), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('hash')
                    )
    op.create_index(op.f('ix_hash_hash'), 'hash', ['hash'], unique=False)
    op.alter_column('dish', 'price',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=2),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish', 'price',
                    existing_type=sa.Float(precision=2),
                    type_=sa.REAL(),
                    existing_nullable=False)
    op.drop_index(op.f('ix_hash_hash'), table_name='hash')
    op.drop_table('hash')
    # ### end Alembic commands ###
